app_port: 6000
debug: false

# 'logrus' | 'zap'
#log_channel: "logrus"

profile_enabled: true

# 如果在集群外部，则需要配置，否则不用
kubeconfig: ""

# database
# 'sqlite' or 'mysql', 如果是 'sqlite', 'db_database' 为 db 绝对路径
db_driver: "sqlite"
db_database: /tmp/mars-sqlite.db
# 如果是 'mysql' 以下均为必填项，如果是 'sqlite' 就不用填
db_host: 127.0.0.1
db_port: 3306
db_username: root
db_password: ""

# 通配符域名，自动生成对应命名空间下的 https 域名
wildcard_domain: "*.test.local"
# cert-manager 的 cluster_issuer 名称
cluster_issuer: "prod"
# 集群外网访问 ip
external_ip: "127.0.0.1"

install_timeout: 90s

gitlab_token: ""
gitlab_baseurl: "https://gitlab.com/api/v4"

# imagepullsecrets: docker 私有镜像仓库需要配置相关的账号密码以及仓库地址
imagepullsecrets:
  - username: "jack"
    password: "12345"
    email: "jack@example.com"
    server: "registry.cn-hangzhou.aliyuncs.com"
  - username: "john"
    password: "12345"
    email: "john@example.com"
    server: "registry.cn-hangzhou.aliyuncs.com"