// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/duc-cnzj/mars/v5/internal/ent/favorite"
	"github.com/duc-cnzj/mars/v5/internal/ent/namespace"
	"github.com/duc-cnzj/mars/v5/internal/ent/predicate"
)

// FavoriteUpdate is the builder for updating Favorite entities.
type FavoriteUpdate struct {
	config
	hooks    []Hook
	mutation *FavoriteMutation
}

// Where appends a list predicates to the FavoriteUpdate builder.
func (fu *FavoriteUpdate) Where(ps ...predicate.Favorite) *FavoriteUpdate {
	fu.mutation.Where(ps...)
	return fu
}

// SetEmail sets the "email" field.
func (fu *FavoriteUpdate) SetEmail(s string) *FavoriteUpdate {
	fu.mutation.SetEmail(s)
	return fu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (fu *FavoriteUpdate) SetNillableEmail(s *string) *FavoriteUpdate {
	if s != nil {
		fu.SetEmail(*s)
	}
	return fu
}

// SetNamespaceID sets the "namespace_id" field.
func (fu *FavoriteUpdate) SetNamespaceID(i int) *FavoriteUpdate {
	fu.mutation.SetNamespaceID(i)
	return fu
}

// SetNillableNamespaceID sets the "namespace_id" field if the given value is not nil.
func (fu *FavoriteUpdate) SetNillableNamespaceID(i *int) *FavoriteUpdate {
	if i != nil {
		fu.SetNamespaceID(*i)
	}
	return fu
}

// ClearNamespaceID clears the value of the "namespace_id" field.
func (fu *FavoriteUpdate) ClearNamespaceID() *FavoriteUpdate {
	fu.mutation.ClearNamespaceID()
	return fu
}

// SetNamespace sets the "namespace" edge to the Namespace entity.
func (fu *FavoriteUpdate) SetNamespace(n *Namespace) *FavoriteUpdate {
	return fu.SetNamespaceID(n.ID)
}

// Mutation returns the FavoriteMutation object of the builder.
func (fu *FavoriteUpdate) Mutation() *FavoriteMutation {
	return fu.mutation
}

// ClearNamespace clears the "namespace" edge to the Namespace entity.
func (fu *FavoriteUpdate) ClearNamespace() *FavoriteUpdate {
	fu.mutation.ClearNamespace()
	return fu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fu *FavoriteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, fu.sqlSave, fu.mutation, fu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FavoriteUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FavoriteUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FavoriteUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fu *FavoriteUpdate) check() error {
	if v, ok := fu.mutation.Email(); ok {
		if err := favorite.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Favorite.email": %w`, err)}
		}
	}
	return nil
}

func (fu *FavoriteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := fu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(favorite.Table, favorite.Columns, sqlgraph.NewFieldSpec(favorite.FieldID, field.TypeInt))
	if ps := fu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.Email(); ok {
		_spec.SetField(favorite.FieldEmail, field.TypeString, value)
	}
	if fu.mutation.NamespaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favorite.NamespaceTable,
			Columns: []string{favorite.NamespaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(namespace.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.NamespaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favorite.NamespaceTable,
			Columns: []string{favorite.NamespaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(namespace.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{favorite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fu.mutation.done = true
	return n, nil
}

// FavoriteUpdateOne is the builder for updating a single Favorite entity.
type FavoriteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FavoriteMutation
}

// SetEmail sets the "email" field.
func (fuo *FavoriteUpdateOne) SetEmail(s string) *FavoriteUpdateOne {
	fuo.mutation.SetEmail(s)
	return fuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (fuo *FavoriteUpdateOne) SetNillableEmail(s *string) *FavoriteUpdateOne {
	if s != nil {
		fuo.SetEmail(*s)
	}
	return fuo
}

// SetNamespaceID sets the "namespace_id" field.
func (fuo *FavoriteUpdateOne) SetNamespaceID(i int) *FavoriteUpdateOne {
	fuo.mutation.SetNamespaceID(i)
	return fuo
}

// SetNillableNamespaceID sets the "namespace_id" field if the given value is not nil.
func (fuo *FavoriteUpdateOne) SetNillableNamespaceID(i *int) *FavoriteUpdateOne {
	if i != nil {
		fuo.SetNamespaceID(*i)
	}
	return fuo
}

// ClearNamespaceID clears the value of the "namespace_id" field.
func (fuo *FavoriteUpdateOne) ClearNamespaceID() *FavoriteUpdateOne {
	fuo.mutation.ClearNamespaceID()
	return fuo
}

// SetNamespace sets the "namespace" edge to the Namespace entity.
func (fuo *FavoriteUpdateOne) SetNamespace(n *Namespace) *FavoriteUpdateOne {
	return fuo.SetNamespaceID(n.ID)
}

// Mutation returns the FavoriteMutation object of the builder.
func (fuo *FavoriteUpdateOne) Mutation() *FavoriteMutation {
	return fuo.mutation
}

// ClearNamespace clears the "namespace" edge to the Namespace entity.
func (fuo *FavoriteUpdateOne) ClearNamespace() *FavoriteUpdateOne {
	fuo.mutation.ClearNamespace()
	return fuo
}

// Where appends a list predicates to the FavoriteUpdate builder.
func (fuo *FavoriteUpdateOne) Where(ps ...predicate.Favorite) *FavoriteUpdateOne {
	fuo.mutation.Where(ps...)
	return fuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fuo *FavoriteUpdateOne) Select(field string, fields ...string) *FavoriteUpdateOne {
	fuo.fields = append([]string{field}, fields...)
	return fuo
}

// Save executes the query and returns the updated Favorite entity.
func (fuo *FavoriteUpdateOne) Save(ctx context.Context) (*Favorite, error) {
	return withHooks(ctx, fuo.sqlSave, fuo.mutation, fuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FavoriteUpdateOne) SaveX(ctx context.Context) *Favorite {
	node, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fuo *FavoriteUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FavoriteUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fuo *FavoriteUpdateOne) check() error {
	if v, ok := fuo.mutation.Email(); ok {
		if err := favorite.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Favorite.email": %w`, err)}
		}
	}
	return nil
}

func (fuo *FavoriteUpdateOne) sqlSave(ctx context.Context) (_node *Favorite, err error) {
	if err := fuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(favorite.Table, favorite.Columns, sqlgraph.NewFieldSpec(favorite.FieldID, field.TypeInt))
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Favorite.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, favorite.FieldID)
		for _, f := range fields {
			if !favorite.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != favorite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fuo.mutation.Email(); ok {
		_spec.SetField(favorite.FieldEmail, field.TypeString, value)
	}
	if fuo.mutation.NamespaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favorite.NamespaceTable,
			Columns: []string{favorite.NamespaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(namespace.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.NamespaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favorite.NamespaceTable,
			Columns: []string{favorite.NamespaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(namespace.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Favorite{config: fuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{favorite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fuo.mutation.done = true
	return _node, nil
}
