// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/duc-cnzj/mars/api/v6/proto/types"
	"github.com/duc-cnzj/mars/api/v6/proto/websocket"
	"github.com/duc-cnzj/mars/v6/internal/data/ent/changelog"
	"github.com/duc-cnzj/mars/v6/internal/data/ent/namespace"
	"github.com/duc-cnzj/mars/v6/internal/data/ent/project"
	"github.com/duc-cnzj/mars/v6/internal/data/ent/repo"
)

// ProjectCreate is the builder for creating a Project entity.
type ProjectCreate struct {
	config
	mutation *ProjectMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectCreate) SetCreatedAt(v time.Time) *ProjectCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableCreatedAt(v *time.Time) *ProjectCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProjectCreate) SetUpdatedAt(v time.Time) *ProjectCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableUpdatedAt(v *time.Time) *ProjectCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ProjectCreate) SetDeletedAt(v time.Time) *ProjectCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableDeletedAt(v *time.Time) *ProjectCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ProjectCreate) SetName(v string) *ProjectCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableName(v *string) *ProjectCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetGitProjectID sets the "git_project_id" field.
func (_c *ProjectCreate) SetGitProjectID(v int) *ProjectCreate {
	_c.mutation.SetGitProjectID(v)
	return _c
}

// SetNillableGitProjectID sets the "git_project_id" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableGitProjectID(v *int) *ProjectCreate {
	if v != nil {
		_c.SetGitProjectID(*v)
	}
	return _c
}

// SetGitBranch sets the "git_branch" field.
func (_c *ProjectCreate) SetGitBranch(v string) *ProjectCreate {
	_c.mutation.SetGitBranch(v)
	return _c
}

// SetNillableGitBranch sets the "git_branch" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableGitBranch(v *string) *ProjectCreate {
	if v != nil {
		_c.SetGitBranch(*v)
	}
	return _c
}

// SetGitCommit sets the "git_commit" field.
func (_c *ProjectCreate) SetGitCommit(v string) *ProjectCreate {
	_c.mutation.SetGitCommit(v)
	return _c
}

// SetNillableGitCommit sets the "git_commit" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableGitCommit(v *string) *ProjectCreate {
	if v != nil {
		_c.SetGitCommit(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *ProjectCreate) SetConfig(v string) *ProjectCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableConfig(v *string) *ProjectCreate {
	if v != nil {
		_c.SetConfig(*v)
	}
	return _c
}

// SetCreator sets the "creator" field.
func (_c *ProjectCreate) SetCreator(v string) *ProjectCreate {
	_c.mutation.SetCreator(v)
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ProjectCreate) SetUpdatedBy(v string) *ProjectCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableUpdatedBy(v *string) *ProjectCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetOverrideValues sets the "override_values" field.
func (_c *ProjectCreate) SetOverrideValues(v string) *ProjectCreate {
	_c.mutation.SetOverrideValues(v)
	return _c
}

// SetNillableOverrideValues sets the "override_values" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableOverrideValues(v *string) *ProjectCreate {
	if v != nil {
		_c.SetOverrideValues(*v)
	}
	return _c
}

// SetDockerImage sets the "docker_image" field.
func (_c *ProjectCreate) SetDockerImage(v []string) *ProjectCreate {
	_c.mutation.SetDockerImage(v)
	return _c
}

// SetPodSelectors sets the "pod_selectors" field.
func (_c *ProjectCreate) SetPodSelectors(v []string) *ProjectCreate {
	_c.mutation.SetPodSelectors(v)
	return _c
}

// SetAtomic sets the "atomic" field.
func (_c *ProjectCreate) SetAtomic(v bool) *ProjectCreate {
	_c.mutation.SetAtomic(v)
	return _c
}

// SetNillableAtomic sets the "atomic" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableAtomic(v *bool) *ProjectCreate {
	if v != nil {
		_c.SetAtomic(*v)
	}
	return _c
}

// SetDeployStatus sets the "deploy_status" field.
func (_c *ProjectCreate) SetDeployStatus(v types.Deploy) *ProjectCreate {
	_c.mutation.SetDeployStatus(v)
	return _c
}

// SetNillableDeployStatus sets the "deploy_status" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableDeployStatus(v *types.Deploy) *ProjectCreate {
	if v != nil {
		_c.SetDeployStatus(*v)
	}
	return _c
}

// SetEnvValues sets the "env_values" field.
func (_c *ProjectCreate) SetEnvValues(v []*types.KeyValue) *ProjectCreate {
	_c.mutation.SetEnvValues(v)
	return _c
}

// SetExtraValues sets the "extra_values" field.
func (_c *ProjectCreate) SetExtraValues(v []*websocket.ExtraValue) *ProjectCreate {
	_c.mutation.SetExtraValues(v)
	return _c
}

// SetFinalExtraValues sets the "final_extra_values" field.
func (_c *ProjectCreate) SetFinalExtraValues(v []*websocket.ExtraValue) *ProjectCreate {
	_c.mutation.SetFinalExtraValues(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *ProjectCreate) SetVersion(v int) *ProjectCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableVersion(v *int) *ProjectCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetConfigType sets the "config_type" field.
func (_c *ProjectCreate) SetConfigType(v string) *ProjectCreate {
	_c.mutation.SetConfigType(v)
	return _c
}

// SetNillableConfigType sets the "config_type" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableConfigType(v *string) *ProjectCreate {
	if v != nil {
		_c.SetConfigType(*v)
	}
	return _c
}

// SetManifest sets the "manifest" field.
func (_c *ProjectCreate) SetManifest(v []string) *ProjectCreate {
	_c.mutation.SetManifest(v)
	return _c
}

// SetGitCommitWebURL sets the "git_commit_web_url" field.
func (_c *ProjectCreate) SetGitCommitWebURL(v string) *ProjectCreate {
	_c.mutation.SetGitCommitWebURL(v)
	return _c
}

// SetNillableGitCommitWebURL sets the "git_commit_web_url" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableGitCommitWebURL(v *string) *ProjectCreate {
	if v != nil {
		_c.SetGitCommitWebURL(*v)
	}
	return _c
}

// SetGitCommitTitle sets the "git_commit_title" field.
func (_c *ProjectCreate) SetGitCommitTitle(v string) *ProjectCreate {
	_c.mutation.SetGitCommitTitle(v)
	return _c
}

// SetNillableGitCommitTitle sets the "git_commit_title" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableGitCommitTitle(v *string) *ProjectCreate {
	if v != nil {
		_c.SetGitCommitTitle(*v)
	}
	return _c
}

// SetGitCommitAuthor sets the "git_commit_author" field.
func (_c *ProjectCreate) SetGitCommitAuthor(v string) *ProjectCreate {
	_c.mutation.SetGitCommitAuthor(v)
	return _c
}

// SetNillableGitCommitAuthor sets the "git_commit_author" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableGitCommitAuthor(v *string) *ProjectCreate {
	if v != nil {
		_c.SetGitCommitAuthor(*v)
	}
	return _c
}

// SetGitCommitDate sets the "git_commit_date" field.
func (_c *ProjectCreate) SetGitCommitDate(v time.Time) *ProjectCreate {
	_c.mutation.SetGitCommitDate(v)
	return _c
}

// SetNillableGitCommitDate sets the "git_commit_date" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableGitCommitDate(v *time.Time) *ProjectCreate {
	if v != nil {
		_c.SetGitCommitDate(*v)
	}
	return _c
}

// SetNamespaceID sets the "namespace_id" field.
func (_c *ProjectCreate) SetNamespaceID(v int) *ProjectCreate {
	_c.mutation.SetNamespaceID(v)
	return _c
}

// SetNillableNamespaceID sets the "namespace_id" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableNamespaceID(v *int) *ProjectCreate {
	if v != nil {
		_c.SetNamespaceID(*v)
	}
	return _c
}

// SetRepoID sets the "repo_id" field.
func (_c *ProjectCreate) SetRepoID(v int) *ProjectCreate {
	_c.mutation.SetRepoID(v)
	return _c
}

// SetNillableRepoID sets the "repo_id" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableRepoID(v *int) *ProjectCreate {
	if v != nil {
		_c.SetRepoID(*v)
	}
	return _c
}

// AddChangelogIDs adds the "changelogs" edge to the Changelog entity by IDs.
func (_c *ProjectCreate) AddChangelogIDs(ids ...int) *ProjectCreate {
	_c.mutation.AddChangelogIDs(ids...)
	return _c
}

// AddChangelogs adds the "changelogs" edges to the Changelog entity.
func (_c *ProjectCreate) AddChangelogs(v ...*Changelog) *ProjectCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChangelogIDs(ids...)
}

// SetRepo sets the "repo" edge to the Repo entity.
func (_c *ProjectCreate) SetRepo(v *Repo) *ProjectCreate {
	return _c.SetRepoID(v.ID)
}

// SetNamespace sets the "namespace" edge to the Namespace entity.
func (_c *ProjectCreate) SetNamespace(v *Namespace) *ProjectCreate {
	return _c.SetNamespaceID(v.ID)
}

// Mutation returns the ProjectMutation object of the builder.
func (_c *ProjectCreate) Mutation() *ProjectMutation {
	return _c.mutation
}

// Save creates the Project in the database.
func (_c *ProjectCreate) Save(ctx context.Context) (*Project, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectCreate) SaveX(ctx context.Context) *Project {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if project.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized project.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := project.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if project.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized project.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := project.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Name(); !ok {
		v := project.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Atomic(); !ok {
		v := project.DefaultAtomic
		_c.mutation.SetAtomic(v)
	}
	if _, ok := _c.mutation.DeployStatus(); !ok {
		v := project.DefaultDeployStatus
		_c.mutation.SetDeployStatus(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := project.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.GitCommitWebURL(); !ok {
		v := project.DefaultGitCommitWebURL
		_c.mutation.SetGitCommitWebURL(v)
	}
	if _, ok := _c.mutation.GitCommitAuthor(); !ok {
		v := project.DefaultGitCommitAuthor
		_c.mutation.SetGitCommitAuthor(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Project.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Project.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Project.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.GitBranch(); ok {
		if err := project.GitBranchValidator(v); err != nil {
			return &ValidationError{Name: "git_branch", err: fmt.Errorf(`ent: validator failed for field "Project.git_branch": %w`, err)}
		}
	}
	if v, ok := _c.mutation.GitCommit(); ok {
		if err := project.GitCommitValidator(v); err != nil {
			return &ValidationError{Name: "git_commit", err: fmt.Errorf(`ent: validator failed for field "Project.git_commit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Creator(); !ok {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required field "Project.creator"`)}
	}
	if v, ok := _c.mutation.UpdatedBy(); ok {
		if err := project.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "Project.updated_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Atomic(); !ok {
		return &ValidationError{Name: "atomic", err: errors.New(`ent: missing required field "Project.atomic"`)}
	}
	if _, ok := _c.mutation.DeployStatus(); !ok {
		return &ValidationError{Name: "deploy_status", err: errors.New(`ent: missing required field "Project.deploy_status"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Project.version"`)}
	}
	if v, ok := _c.mutation.ConfigType(); ok {
		if err := project.ConfigTypeValidator(v); err != nil {
			return &ValidationError{Name: "config_type", err: fmt.Errorf(`ent: validator failed for field "Project.config_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GitCommitWebURL(); !ok {
		return &ValidationError{Name: "git_commit_web_url", err: errors.New(`ent: missing required field "Project.git_commit_web_url"`)}
	}
	if v, ok := _c.mutation.GitCommitWebURL(); ok {
		if err := project.GitCommitWebURLValidator(v); err != nil {
			return &ValidationError{Name: "git_commit_web_url", err: fmt.Errorf(`ent: validator failed for field "Project.git_commit_web_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GitCommitAuthor(); !ok {
		return &ValidationError{Name: "git_commit_author", err: errors.New(`ent: missing required field "Project.git_commit_author"`)}
	}
	if v, ok := _c.mutation.GitCommitAuthor(); ok {
		if err := project.GitCommitAuthorValidator(v); err != nil {
			return &ValidationError{Name: "git_commit_author", err: fmt.Errorf(`ent: validator failed for field "Project.git_commit_author": %w`, err)}
		}
	}
	return nil
}

func (_c *ProjectCreate) sqlSave(ctx context.Context) (*Project, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectCreate) createSpec() (*Project, *sqlgraph.CreateSpec) {
	var (
		_node = &Project{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(project.Table, sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(project.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(project.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GitProjectID(); ok {
		_spec.SetField(project.FieldGitProjectID, field.TypeInt, value)
		_node.GitProjectID = value
	}
	if value, ok := _c.mutation.GitBranch(); ok {
		_spec.SetField(project.FieldGitBranch, field.TypeString, value)
		_node.GitBranch = value
	}
	if value, ok := _c.mutation.GitCommit(); ok {
		_spec.SetField(project.FieldGitCommit, field.TypeString, value)
		_node.GitCommit = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(project.FieldConfig, field.TypeString, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.Creator(); ok {
		_spec.SetField(project.FieldCreator, field.TypeString, value)
		_node.Creator = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(project.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.OverrideValues(); ok {
		_spec.SetField(project.FieldOverrideValues, field.TypeString, value)
		_node.OverrideValues = value
	}
	if value, ok := _c.mutation.DockerImage(); ok {
		_spec.SetField(project.FieldDockerImage, field.TypeJSON, value)
		_node.DockerImage = value
	}
	if value, ok := _c.mutation.PodSelectors(); ok {
		_spec.SetField(project.FieldPodSelectors, field.TypeJSON, value)
		_node.PodSelectors = value
	}
	if value, ok := _c.mutation.Atomic(); ok {
		_spec.SetField(project.FieldAtomic, field.TypeBool, value)
		_node.Atomic = value
	}
	if value, ok := _c.mutation.DeployStatus(); ok {
		_spec.SetField(project.FieldDeployStatus, field.TypeInt32, value)
		_node.DeployStatus = value
	}
	if value, ok := _c.mutation.EnvValues(); ok {
		_spec.SetField(project.FieldEnvValues, field.TypeJSON, value)
		_node.EnvValues = value
	}
	if value, ok := _c.mutation.ExtraValues(); ok {
		_spec.SetField(project.FieldExtraValues, field.TypeJSON, value)
		_node.ExtraValues = value
	}
	if value, ok := _c.mutation.FinalExtraValues(); ok {
		_spec.SetField(project.FieldFinalExtraValues, field.TypeJSON, value)
		_node.FinalExtraValues = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(project.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.ConfigType(); ok {
		_spec.SetField(project.FieldConfigType, field.TypeString, value)
		_node.ConfigType = value
	}
	if value, ok := _c.mutation.Manifest(); ok {
		_spec.SetField(project.FieldManifest, field.TypeJSON, value)
		_node.Manifest = value
	}
	if value, ok := _c.mutation.GitCommitWebURL(); ok {
		_spec.SetField(project.FieldGitCommitWebURL, field.TypeString, value)
		_node.GitCommitWebURL = value
	}
	if value, ok := _c.mutation.GitCommitTitle(); ok {
		_spec.SetField(project.FieldGitCommitTitle, field.TypeString, value)
		_node.GitCommitTitle = value
	}
	if value, ok := _c.mutation.GitCommitAuthor(); ok {
		_spec.SetField(project.FieldGitCommitAuthor, field.TypeString, value)
		_node.GitCommitAuthor = value
	}
	if value, ok := _c.mutation.GitCommitDate(); ok {
		_spec.SetField(project.FieldGitCommitDate, field.TypeTime, value)
		_node.GitCommitDate = &value
	}
	if nodes := _c.mutation.ChangelogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.ChangelogsTable,
			Columns: []string{project.ChangelogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RepoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.RepoTable,
			Columns: []string{project.RepoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repo.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RepoID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NamespaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.NamespaceTable,
			Columns: []string{project.NamespaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(namespace.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NamespaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Project.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProjectUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProjectCreate) OnConflict(opts ...sql.ConflictOption) *ProjectUpsertOne {
	_c.conflict = opts
	return &ProjectUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Project.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProjectCreate) OnConflictColumns(columns ...string) *ProjectUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProjectUpsertOne{
		create: _c,
	}
}

type (
	// ProjectUpsertOne is the builder for "upsert"-ing
	//  one Project node.
	ProjectUpsertOne struct {
		create *ProjectCreate
	}

	// ProjectUpsert is the "OnConflict" setter.
	ProjectUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProjectUpsert) SetUpdatedAt(v time.Time) *ProjectUpsert {
	u.Set(project.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateUpdatedAt() *ProjectUpsert {
	u.SetExcluded(project.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProjectUpsert) SetDeletedAt(v time.Time) *ProjectUpsert {
	u.Set(project.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateDeletedAt() *ProjectUpsert {
	u.SetExcluded(project.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProjectUpsert) ClearDeletedAt() *ProjectUpsert {
	u.SetNull(project.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *ProjectUpsert) SetName(v string) *ProjectUpsert {
	u.Set(project.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateName() *ProjectUpsert {
	u.SetExcluded(project.FieldName)
	return u
}

// SetGitProjectID sets the "git_project_id" field.
func (u *ProjectUpsert) SetGitProjectID(v int) *ProjectUpsert {
	u.Set(project.FieldGitProjectID, v)
	return u
}

// UpdateGitProjectID sets the "git_project_id" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateGitProjectID() *ProjectUpsert {
	u.SetExcluded(project.FieldGitProjectID)
	return u
}

// AddGitProjectID adds v to the "git_project_id" field.
func (u *ProjectUpsert) AddGitProjectID(v int) *ProjectUpsert {
	u.Add(project.FieldGitProjectID, v)
	return u
}

// ClearGitProjectID clears the value of the "git_project_id" field.
func (u *ProjectUpsert) ClearGitProjectID() *ProjectUpsert {
	u.SetNull(project.FieldGitProjectID)
	return u
}

// SetGitBranch sets the "git_branch" field.
func (u *ProjectUpsert) SetGitBranch(v string) *ProjectUpsert {
	u.Set(project.FieldGitBranch, v)
	return u
}

// UpdateGitBranch sets the "git_branch" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateGitBranch() *ProjectUpsert {
	u.SetExcluded(project.FieldGitBranch)
	return u
}

// ClearGitBranch clears the value of the "git_branch" field.
func (u *ProjectUpsert) ClearGitBranch() *ProjectUpsert {
	u.SetNull(project.FieldGitBranch)
	return u
}

// SetGitCommit sets the "git_commit" field.
func (u *ProjectUpsert) SetGitCommit(v string) *ProjectUpsert {
	u.Set(project.FieldGitCommit, v)
	return u
}

// UpdateGitCommit sets the "git_commit" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateGitCommit() *ProjectUpsert {
	u.SetExcluded(project.FieldGitCommit)
	return u
}

// ClearGitCommit clears the value of the "git_commit" field.
func (u *ProjectUpsert) ClearGitCommit() *ProjectUpsert {
	u.SetNull(project.FieldGitCommit)
	return u
}

// SetConfig sets the "config" field.
func (u *ProjectUpsert) SetConfig(v string) *ProjectUpsert {
	u.Set(project.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateConfig() *ProjectUpsert {
	u.SetExcluded(project.FieldConfig)
	return u
}

// ClearConfig clears the value of the "config" field.
func (u *ProjectUpsert) ClearConfig() *ProjectUpsert {
	u.SetNull(project.FieldConfig)
	return u
}

// SetCreator sets the "creator" field.
func (u *ProjectUpsert) SetCreator(v string) *ProjectUpsert {
	u.Set(project.FieldCreator, v)
	return u
}

// UpdateCreator sets the "creator" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateCreator() *ProjectUpsert {
	u.SetExcluded(project.FieldCreator)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ProjectUpsert) SetUpdatedBy(v string) *ProjectUpsert {
	u.Set(project.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateUpdatedBy() *ProjectUpsert {
	u.SetExcluded(project.FieldUpdatedBy)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ProjectUpsert) ClearUpdatedBy() *ProjectUpsert {
	u.SetNull(project.FieldUpdatedBy)
	return u
}

// SetOverrideValues sets the "override_values" field.
func (u *ProjectUpsert) SetOverrideValues(v string) *ProjectUpsert {
	u.Set(project.FieldOverrideValues, v)
	return u
}

// UpdateOverrideValues sets the "override_values" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateOverrideValues() *ProjectUpsert {
	u.SetExcluded(project.FieldOverrideValues)
	return u
}

// ClearOverrideValues clears the value of the "override_values" field.
func (u *ProjectUpsert) ClearOverrideValues() *ProjectUpsert {
	u.SetNull(project.FieldOverrideValues)
	return u
}

// SetDockerImage sets the "docker_image" field.
func (u *ProjectUpsert) SetDockerImage(v []string) *ProjectUpsert {
	u.Set(project.FieldDockerImage, v)
	return u
}

// UpdateDockerImage sets the "docker_image" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateDockerImage() *ProjectUpsert {
	u.SetExcluded(project.FieldDockerImage)
	return u
}

// ClearDockerImage clears the value of the "docker_image" field.
func (u *ProjectUpsert) ClearDockerImage() *ProjectUpsert {
	u.SetNull(project.FieldDockerImage)
	return u
}

// SetPodSelectors sets the "pod_selectors" field.
func (u *ProjectUpsert) SetPodSelectors(v []string) *ProjectUpsert {
	u.Set(project.FieldPodSelectors, v)
	return u
}

// UpdatePodSelectors sets the "pod_selectors" field to the value that was provided on create.
func (u *ProjectUpsert) UpdatePodSelectors() *ProjectUpsert {
	u.SetExcluded(project.FieldPodSelectors)
	return u
}

// ClearPodSelectors clears the value of the "pod_selectors" field.
func (u *ProjectUpsert) ClearPodSelectors() *ProjectUpsert {
	u.SetNull(project.FieldPodSelectors)
	return u
}

// SetAtomic sets the "atomic" field.
func (u *ProjectUpsert) SetAtomic(v bool) *ProjectUpsert {
	u.Set(project.FieldAtomic, v)
	return u
}

// UpdateAtomic sets the "atomic" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateAtomic() *ProjectUpsert {
	u.SetExcluded(project.FieldAtomic)
	return u
}

// SetDeployStatus sets the "deploy_status" field.
func (u *ProjectUpsert) SetDeployStatus(v types.Deploy) *ProjectUpsert {
	u.Set(project.FieldDeployStatus, v)
	return u
}

// UpdateDeployStatus sets the "deploy_status" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateDeployStatus() *ProjectUpsert {
	u.SetExcluded(project.FieldDeployStatus)
	return u
}

// AddDeployStatus adds v to the "deploy_status" field.
func (u *ProjectUpsert) AddDeployStatus(v types.Deploy) *ProjectUpsert {
	u.Add(project.FieldDeployStatus, v)
	return u
}

// SetEnvValues sets the "env_values" field.
func (u *ProjectUpsert) SetEnvValues(v []*types.KeyValue) *ProjectUpsert {
	u.Set(project.FieldEnvValues, v)
	return u
}

// UpdateEnvValues sets the "env_values" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateEnvValues() *ProjectUpsert {
	u.SetExcluded(project.FieldEnvValues)
	return u
}

// ClearEnvValues clears the value of the "env_values" field.
func (u *ProjectUpsert) ClearEnvValues() *ProjectUpsert {
	u.SetNull(project.FieldEnvValues)
	return u
}

// SetExtraValues sets the "extra_values" field.
func (u *ProjectUpsert) SetExtraValues(v []*websocket.ExtraValue) *ProjectUpsert {
	u.Set(project.FieldExtraValues, v)
	return u
}

// UpdateExtraValues sets the "extra_values" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateExtraValues() *ProjectUpsert {
	u.SetExcluded(project.FieldExtraValues)
	return u
}

// ClearExtraValues clears the value of the "extra_values" field.
func (u *ProjectUpsert) ClearExtraValues() *ProjectUpsert {
	u.SetNull(project.FieldExtraValues)
	return u
}

// SetFinalExtraValues sets the "final_extra_values" field.
func (u *ProjectUpsert) SetFinalExtraValues(v []*websocket.ExtraValue) *ProjectUpsert {
	u.Set(project.FieldFinalExtraValues, v)
	return u
}

// UpdateFinalExtraValues sets the "final_extra_values" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateFinalExtraValues() *ProjectUpsert {
	u.SetExcluded(project.FieldFinalExtraValues)
	return u
}

// ClearFinalExtraValues clears the value of the "final_extra_values" field.
func (u *ProjectUpsert) ClearFinalExtraValues() *ProjectUpsert {
	u.SetNull(project.FieldFinalExtraValues)
	return u
}

// SetVersion sets the "version" field.
func (u *ProjectUpsert) SetVersion(v int) *ProjectUpsert {
	u.Set(project.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateVersion() *ProjectUpsert {
	u.SetExcluded(project.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *ProjectUpsert) AddVersion(v int) *ProjectUpsert {
	u.Add(project.FieldVersion, v)
	return u
}

// SetConfigType sets the "config_type" field.
func (u *ProjectUpsert) SetConfigType(v string) *ProjectUpsert {
	u.Set(project.FieldConfigType, v)
	return u
}

// UpdateConfigType sets the "config_type" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateConfigType() *ProjectUpsert {
	u.SetExcluded(project.FieldConfigType)
	return u
}

// ClearConfigType clears the value of the "config_type" field.
func (u *ProjectUpsert) ClearConfigType() *ProjectUpsert {
	u.SetNull(project.FieldConfigType)
	return u
}

// SetManifest sets the "manifest" field.
func (u *ProjectUpsert) SetManifest(v []string) *ProjectUpsert {
	u.Set(project.FieldManifest, v)
	return u
}

// UpdateManifest sets the "manifest" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateManifest() *ProjectUpsert {
	u.SetExcluded(project.FieldManifest)
	return u
}

// ClearManifest clears the value of the "manifest" field.
func (u *ProjectUpsert) ClearManifest() *ProjectUpsert {
	u.SetNull(project.FieldManifest)
	return u
}

// SetGitCommitWebURL sets the "git_commit_web_url" field.
func (u *ProjectUpsert) SetGitCommitWebURL(v string) *ProjectUpsert {
	u.Set(project.FieldGitCommitWebURL, v)
	return u
}

// UpdateGitCommitWebURL sets the "git_commit_web_url" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateGitCommitWebURL() *ProjectUpsert {
	u.SetExcluded(project.FieldGitCommitWebURL)
	return u
}

// SetGitCommitTitle sets the "git_commit_title" field.
func (u *ProjectUpsert) SetGitCommitTitle(v string) *ProjectUpsert {
	u.Set(project.FieldGitCommitTitle, v)
	return u
}

// UpdateGitCommitTitle sets the "git_commit_title" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateGitCommitTitle() *ProjectUpsert {
	u.SetExcluded(project.FieldGitCommitTitle)
	return u
}

// ClearGitCommitTitle clears the value of the "git_commit_title" field.
func (u *ProjectUpsert) ClearGitCommitTitle() *ProjectUpsert {
	u.SetNull(project.FieldGitCommitTitle)
	return u
}

// SetGitCommitAuthor sets the "git_commit_author" field.
func (u *ProjectUpsert) SetGitCommitAuthor(v string) *ProjectUpsert {
	u.Set(project.FieldGitCommitAuthor, v)
	return u
}

// UpdateGitCommitAuthor sets the "git_commit_author" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateGitCommitAuthor() *ProjectUpsert {
	u.SetExcluded(project.FieldGitCommitAuthor)
	return u
}

// SetGitCommitDate sets the "git_commit_date" field.
func (u *ProjectUpsert) SetGitCommitDate(v time.Time) *ProjectUpsert {
	u.Set(project.FieldGitCommitDate, v)
	return u
}

// UpdateGitCommitDate sets the "git_commit_date" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateGitCommitDate() *ProjectUpsert {
	u.SetExcluded(project.FieldGitCommitDate)
	return u
}

// ClearGitCommitDate clears the value of the "git_commit_date" field.
func (u *ProjectUpsert) ClearGitCommitDate() *ProjectUpsert {
	u.SetNull(project.FieldGitCommitDate)
	return u
}

// SetNamespaceID sets the "namespace_id" field.
func (u *ProjectUpsert) SetNamespaceID(v int) *ProjectUpsert {
	u.Set(project.FieldNamespaceID, v)
	return u
}

// UpdateNamespaceID sets the "namespace_id" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateNamespaceID() *ProjectUpsert {
	u.SetExcluded(project.FieldNamespaceID)
	return u
}

// ClearNamespaceID clears the value of the "namespace_id" field.
func (u *ProjectUpsert) ClearNamespaceID() *ProjectUpsert {
	u.SetNull(project.FieldNamespaceID)
	return u
}

// SetRepoID sets the "repo_id" field.
func (u *ProjectUpsert) SetRepoID(v int) *ProjectUpsert {
	u.Set(project.FieldRepoID, v)
	return u
}

// UpdateRepoID sets the "repo_id" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateRepoID() *ProjectUpsert {
	u.SetExcluded(project.FieldRepoID)
	return u
}

// ClearRepoID clears the value of the "repo_id" field.
func (u *ProjectUpsert) ClearRepoID() *ProjectUpsert {
	u.SetNull(project.FieldRepoID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Project.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProjectUpsertOne) UpdateNewValues() *ProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(project.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Project.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProjectUpsertOne) Ignore() *ProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProjectUpsertOne) DoNothing() *ProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProjectCreate.OnConflict
// documentation for more info.
func (u *ProjectUpsertOne) Update(set func(*ProjectUpsert)) *ProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProjectUpsertOne) SetUpdatedAt(v time.Time) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateUpdatedAt() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProjectUpsertOne) SetDeletedAt(v time.Time) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateDeletedAt() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProjectUpsertOne) ClearDeletedAt() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ProjectUpsertOne) SetName(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateName() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateName()
	})
}

// SetGitProjectID sets the "git_project_id" field.
func (u *ProjectUpsertOne) SetGitProjectID(v int) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetGitProjectID(v)
	})
}

// AddGitProjectID adds v to the "git_project_id" field.
func (u *ProjectUpsertOne) AddGitProjectID(v int) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.AddGitProjectID(v)
	})
}

// UpdateGitProjectID sets the "git_project_id" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateGitProjectID() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateGitProjectID()
	})
}

// ClearGitProjectID clears the value of the "git_project_id" field.
func (u *ProjectUpsertOne) ClearGitProjectID() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearGitProjectID()
	})
}

// SetGitBranch sets the "git_branch" field.
func (u *ProjectUpsertOne) SetGitBranch(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetGitBranch(v)
	})
}

// UpdateGitBranch sets the "git_branch" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateGitBranch() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateGitBranch()
	})
}

// ClearGitBranch clears the value of the "git_branch" field.
func (u *ProjectUpsertOne) ClearGitBranch() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearGitBranch()
	})
}

// SetGitCommit sets the "git_commit" field.
func (u *ProjectUpsertOne) SetGitCommit(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetGitCommit(v)
	})
}

// UpdateGitCommit sets the "git_commit" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateGitCommit() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateGitCommit()
	})
}

// ClearGitCommit clears the value of the "git_commit" field.
func (u *ProjectUpsertOne) ClearGitCommit() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearGitCommit()
	})
}

// SetConfig sets the "config" field.
func (u *ProjectUpsertOne) SetConfig(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateConfig() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateConfig()
	})
}

// ClearConfig clears the value of the "config" field.
func (u *ProjectUpsertOne) ClearConfig() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearConfig()
	})
}

// SetCreator sets the "creator" field.
func (u *ProjectUpsertOne) SetCreator(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetCreator(v)
	})
}

// UpdateCreator sets the "creator" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateCreator() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateCreator()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ProjectUpsertOne) SetUpdatedBy(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateUpdatedBy() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ProjectUpsertOne) ClearUpdatedBy() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetOverrideValues sets the "override_values" field.
func (u *ProjectUpsertOne) SetOverrideValues(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetOverrideValues(v)
	})
}

// UpdateOverrideValues sets the "override_values" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateOverrideValues() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateOverrideValues()
	})
}

// ClearOverrideValues clears the value of the "override_values" field.
func (u *ProjectUpsertOne) ClearOverrideValues() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearOverrideValues()
	})
}

// SetDockerImage sets the "docker_image" field.
func (u *ProjectUpsertOne) SetDockerImage(v []string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetDockerImage(v)
	})
}

// UpdateDockerImage sets the "docker_image" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateDockerImage() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateDockerImage()
	})
}

// ClearDockerImage clears the value of the "docker_image" field.
func (u *ProjectUpsertOne) ClearDockerImage() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearDockerImage()
	})
}

// SetPodSelectors sets the "pod_selectors" field.
func (u *ProjectUpsertOne) SetPodSelectors(v []string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetPodSelectors(v)
	})
}

// UpdatePodSelectors sets the "pod_selectors" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdatePodSelectors() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdatePodSelectors()
	})
}

// ClearPodSelectors clears the value of the "pod_selectors" field.
func (u *ProjectUpsertOne) ClearPodSelectors() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearPodSelectors()
	})
}

// SetAtomic sets the "atomic" field.
func (u *ProjectUpsertOne) SetAtomic(v bool) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetAtomic(v)
	})
}

// UpdateAtomic sets the "atomic" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateAtomic() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateAtomic()
	})
}

// SetDeployStatus sets the "deploy_status" field.
func (u *ProjectUpsertOne) SetDeployStatus(v types.Deploy) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetDeployStatus(v)
	})
}

// AddDeployStatus adds v to the "deploy_status" field.
func (u *ProjectUpsertOne) AddDeployStatus(v types.Deploy) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.AddDeployStatus(v)
	})
}

// UpdateDeployStatus sets the "deploy_status" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateDeployStatus() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateDeployStatus()
	})
}

// SetEnvValues sets the "env_values" field.
func (u *ProjectUpsertOne) SetEnvValues(v []*types.KeyValue) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetEnvValues(v)
	})
}

// UpdateEnvValues sets the "env_values" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateEnvValues() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateEnvValues()
	})
}

// ClearEnvValues clears the value of the "env_values" field.
func (u *ProjectUpsertOne) ClearEnvValues() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearEnvValues()
	})
}

// SetExtraValues sets the "extra_values" field.
func (u *ProjectUpsertOne) SetExtraValues(v []*websocket.ExtraValue) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetExtraValues(v)
	})
}

// UpdateExtraValues sets the "extra_values" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateExtraValues() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateExtraValues()
	})
}

// ClearExtraValues clears the value of the "extra_values" field.
func (u *ProjectUpsertOne) ClearExtraValues() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearExtraValues()
	})
}

// SetFinalExtraValues sets the "final_extra_values" field.
func (u *ProjectUpsertOne) SetFinalExtraValues(v []*websocket.ExtraValue) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetFinalExtraValues(v)
	})
}

// UpdateFinalExtraValues sets the "final_extra_values" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateFinalExtraValues() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateFinalExtraValues()
	})
}

// ClearFinalExtraValues clears the value of the "final_extra_values" field.
func (u *ProjectUpsertOne) ClearFinalExtraValues() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearFinalExtraValues()
	})
}

// SetVersion sets the "version" field.
func (u *ProjectUpsertOne) SetVersion(v int) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ProjectUpsertOne) AddVersion(v int) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateVersion() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateVersion()
	})
}

// SetConfigType sets the "config_type" field.
func (u *ProjectUpsertOne) SetConfigType(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetConfigType(v)
	})
}

// UpdateConfigType sets the "config_type" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateConfigType() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateConfigType()
	})
}

// ClearConfigType clears the value of the "config_type" field.
func (u *ProjectUpsertOne) ClearConfigType() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearConfigType()
	})
}

// SetManifest sets the "manifest" field.
func (u *ProjectUpsertOne) SetManifest(v []string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetManifest(v)
	})
}

// UpdateManifest sets the "manifest" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateManifest() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateManifest()
	})
}

// ClearManifest clears the value of the "manifest" field.
func (u *ProjectUpsertOne) ClearManifest() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearManifest()
	})
}

// SetGitCommitWebURL sets the "git_commit_web_url" field.
func (u *ProjectUpsertOne) SetGitCommitWebURL(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetGitCommitWebURL(v)
	})
}

// UpdateGitCommitWebURL sets the "git_commit_web_url" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateGitCommitWebURL() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateGitCommitWebURL()
	})
}

// SetGitCommitTitle sets the "git_commit_title" field.
func (u *ProjectUpsertOne) SetGitCommitTitle(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetGitCommitTitle(v)
	})
}

// UpdateGitCommitTitle sets the "git_commit_title" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateGitCommitTitle() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateGitCommitTitle()
	})
}

// ClearGitCommitTitle clears the value of the "git_commit_title" field.
func (u *ProjectUpsertOne) ClearGitCommitTitle() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearGitCommitTitle()
	})
}

// SetGitCommitAuthor sets the "git_commit_author" field.
func (u *ProjectUpsertOne) SetGitCommitAuthor(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetGitCommitAuthor(v)
	})
}

// UpdateGitCommitAuthor sets the "git_commit_author" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateGitCommitAuthor() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateGitCommitAuthor()
	})
}

// SetGitCommitDate sets the "git_commit_date" field.
func (u *ProjectUpsertOne) SetGitCommitDate(v time.Time) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetGitCommitDate(v)
	})
}

// UpdateGitCommitDate sets the "git_commit_date" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateGitCommitDate() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateGitCommitDate()
	})
}

// ClearGitCommitDate clears the value of the "git_commit_date" field.
func (u *ProjectUpsertOne) ClearGitCommitDate() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearGitCommitDate()
	})
}

// SetNamespaceID sets the "namespace_id" field.
func (u *ProjectUpsertOne) SetNamespaceID(v int) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetNamespaceID(v)
	})
}

// UpdateNamespaceID sets the "namespace_id" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateNamespaceID() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateNamespaceID()
	})
}

// ClearNamespaceID clears the value of the "namespace_id" field.
func (u *ProjectUpsertOne) ClearNamespaceID() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearNamespaceID()
	})
}

// SetRepoID sets the "repo_id" field.
func (u *ProjectUpsertOne) SetRepoID(v int) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetRepoID(v)
	})
}

// UpdateRepoID sets the "repo_id" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateRepoID() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateRepoID()
	})
}

// ClearRepoID clears the value of the "repo_id" field.
func (u *ProjectUpsertOne) ClearRepoID() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearRepoID()
	})
}

// Exec executes the query.
func (u *ProjectUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProjectCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProjectUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProjectUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProjectUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProjectCreateBulk is the builder for creating many Project entities in bulk.
type ProjectCreateBulk struct {
	config
	err      error
	builders []*ProjectCreate
	conflict []sql.ConflictOption
}

// Save creates the Project entities in the database.
func (_c *ProjectCreateBulk) Save(ctx context.Context) ([]*Project, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Project, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectCreateBulk) SaveX(ctx context.Context) []*Project {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Project.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProjectUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProjectCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProjectUpsertBulk {
	_c.conflict = opts
	return &ProjectUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Project.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProjectCreateBulk) OnConflictColumns(columns ...string) *ProjectUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProjectUpsertBulk{
		create: _c,
	}
}

// ProjectUpsertBulk is the builder for "upsert"-ing
// a bulk of Project nodes.
type ProjectUpsertBulk struct {
	create *ProjectCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Project.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProjectUpsertBulk) UpdateNewValues() *ProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(project.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Project.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProjectUpsertBulk) Ignore() *ProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProjectUpsertBulk) DoNothing() *ProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProjectCreateBulk.OnConflict
// documentation for more info.
func (u *ProjectUpsertBulk) Update(set func(*ProjectUpsert)) *ProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProjectUpsertBulk) SetUpdatedAt(v time.Time) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateUpdatedAt() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProjectUpsertBulk) SetDeletedAt(v time.Time) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateDeletedAt() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProjectUpsertBulk) ClearDeletedAt() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ProjectUpsertBulk) SetName(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateName() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateName()
	})
}

// SetGitProjectID sets the "git_project_id" field.
func (u *ProjectUpsertBulk) SetGitProjectID(v int) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetGitProjectID(v)
	})
}

// AddGitProjectID adds v to the "git_project_id" field.
func (u *ProjectUpsertBulk) AddGitProjectID(v int) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.AddGitProjectID(v)
	})
}

// UpdateGitProjectID sets the "git_project_id" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateGitProjectID() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateGitProjectID()
	})
}

// ClearGitProjectID clears the value of the "git_project_id" field.
func (u *ProjectUpsertBulk) ClearGitProjectID() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearGitProjectID()
	})
}

// SetGitBranch sets the "git_branch" field.
func (u *ProjectUpsertBulk) SetGitBranch(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetGitBranch(v)
	})
}

// UpdateGitBranch sets the "git_branch" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateGitBranch() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateGitBranch()
	})
}

// ClearGitBranch clears the value of the "git_branch" field.
func (u *ProjectUpsertBulk) ClearGitBranch() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearGitBranch()
	})
}

// SetGitCommit sets the "git_commit" field.
func (u *ProjectUpsertBulk) SetGitCommit(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetGitCommit(v)
	})
}

// UpdateGitCommit sets the "git_commit" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateGitCommit() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateGitCommit()
	})
}

// ClearGitCommit clears the value of the "git_commit" field.
func (u *ProjectUpsertBulk) ClearGitCommit() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearGitCommit()
	})
}

// SetConfig sets the "config" field.
func (u *ProjectUpsertBulk) SetConfig(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateConfig() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateConfig()
	})
}

// ClearConfig clears the value of the "config" field.
func (u *ProjectUpsertBulk) ClearConfig() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearConfig()
	})
}

// SetCreator sets the "creator" field.
func (u *ProjectUpsertBulk) SetCreator(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetCreator(v)
	})
}

// UpdateCreator sets the "creator" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateCreator() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateCreator()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ProjectUpsertBulk) SetUpdatedBy(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateUpdatedBy() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ProjectUpsertBulk) ClearUpdatedBy() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetOverrideValues sets the "override_values" field.
func (u *ProjectUpsertBulk) SetOverrideValues(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetOverrideValues(v)
	})
}

// UpdateOverrideValues sets the "override_values" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateOverrideValues() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateOverrideValues()
	})
}

// ClearOverrideValues clears the value of the "override_values" field.
func (u *ProjectUpsertBulk) ClearOverrideValues() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearOverrideValues()
	})
}

// SetDockerImage sets the "docker_image" field.
func (u *ProjectUpsertBulk) SetDockerImage(v []string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetDockerImage(v)
	})
}

// UpdateDockerImage sets the "docker_image" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateDockerImage() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateDockerImage()
	})
}

// ClearDockerImage clears the value of the "docker_image" field.
func (u *ProjectUpsertBulk) ClearDockerImage() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearDockerImage()
	})
}

// SetPodSelectors sets the "pod_selectors" field.
func (u *ProjectUpsertBulk) SetPodSelectors(v []string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetPodSelectors(v)
	})
}

// UpdatePodSelectors sets the "pod_selectors" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdatePodSelectors() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdatePodSelectors()
	})
}

// ClearPodSelectors clears the value of the "pod_selectors" field.
func (u *ProjectUpsertBulk) ClearPodSelectors() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearPodSelectors()
	})
}

// SetAtomic sets the "atomic" field.
func (u *ProjectUpsertBulk) SetAtomic(v bool) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetAtomic(v)
	})
}

// UpdateAtomic sets the "atomic" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateAtomic() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateAtomic()
	})
}

// SetDeployStatus sets the "deploy_status" field.
func (u *ProjectUpsertBulk) SetDeployStatus(v types.Deploy) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetDeployStatus(v)
	})
}

// AddDeployStatus adds v to the "deploy_status" field.
func (u *ProjectUpsertBulk) AddDeployStatus(v types.Deploy) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.AddDeployStatus(v)
	})
}

// UpdateDeployStatus sets the "deploy_status" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateDeployStatus() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateDeployStatus()
	})
}

// SetEnvValues sets the "env_values" field.
func (u *ProjectUpsertBulk) SetEnvValues(v []*types.KeyValue) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetEnvValues(v)
	})
}

// UpdateEnvValues sets the "env_values" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateEnvValues() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateEnvValues()
	})
}

// ClearEnvValues clears the value of the "env_values" field.
func (u *ProjectUpsertBulk) ClearEnvValues() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearEnvValues()
	})
}

// SetExtraValues sets the "extra_values" field.
func (u *ProjectUpsertBulk) SetExtraValues(v []*websocket.ExtraValue) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetExtraValues(v)
	})
}

// UpdateExtraValues sets the "extra_values" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateExtraValues() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateExtraValues()
	})
}

// ClearExtraValues clears the value of the "extra_values" field.
func (u *ProjectUpsertBulk) ClearExtraValues() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearExtraValues()
	})
}

// SetFinalExtraValues sets the "final_extra_values" field.
func (u *ProjectUpsertBulk) SetFinalExtraValues(v []*websocket.ExtraValue) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetFinalExtraValues(v)
	})
}

// UpdateFinalExtraValues sets the "final_extra_values" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateFinalExtraValues() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateFinalExtraValues()
	})
}

// ClearFinalExtraValues clears the value of the "final_extra_values" field.
func (u *ProjectUpsertBulk) ClearFinalExtraValues() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearFinalExtraValues()
	})
}

// SetVersion sets the "version" field.
func (u *ProjectUpsertBulk) SetVersion(v int) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ProjectUpsertBulk) AddVersion(v int) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateVersion() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateVersion()
	})
}

// SetConfigType sets the "config_type" field.
func (u *ProjectUpsertBulk) SetConfigType(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetConfigType(v)
	})
}

// UpdateConfigType sets the "config_type" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateConfigType() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateConfigType()
	})
}

// ClearConfigType clears the value of the "config_type" field.
func (u *ProjectUpsertBulk) ClearConfigType() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearConfigType()
	})
}

// SetManifest sets the "manifest" field.
func (u *ProjectUpsertBulk) SetManifest(v []string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetManifest(v)
	})
}

// UpdateManifest sets the "manifest" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateManifest() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateManifest()
	})
}

// ClearManifest clears the value of the "manifest" field.
func (u *ProjectUpsertBulk) ClearManifest() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearManifest()
	})
}

// SetGitCommitWebURL sets the "git_commit_web_url" field.
func (u *ProjectUpsertBulk) SetGitCommitWebURL(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetGitCommitWebURL(v)
	})
}

// UpdateGitCommitWebURL sets the "git_commit_web_url" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateGitCommitWebURL() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateGitCommitWebURL()
	})
}

// SetGitCommitTitle sets the "git_commit_title" field.
func (u *ProjectUpsertBulk) SetGitCommitTitle(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetGitCommitTitle(v)
	})
}

// UpdateGitCommitTitle sets the "git_commit_title" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateGitCommitTitle() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateGitCommitTitle()
	})
}

// ClearGitCommitTitle clears the value of the "git_commit_title" field.
func (u *ProjectUpsertBulk) ClearGitCommitTitle() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearGitCommitTitle()
	})
}

// SetGitCommitAuthor sets the "git_commit_author" field.
func (u *ProjectUpsertBulk) SetGitCommitAuthor(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetGitCommitAuthor(v)
	})
}

// UpdateGitCommitAuthor sets the "git_commit_author" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateGitCommitAuthor() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateGitCommitAuthor()
	})
}

// SetGitCommitDate sets the "git_commit_date" field.
func (u *ProjectUpsertBulk) SetGitCommitDate(v time.Time) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetGitCommitDate(v)
	})
}

// UpdateGitCommitDate sets the "git_commit_date" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateGitCommitDate() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateGitCommitDate()
	})
}

// ClearGitCommitDate clears the value of the "git_commit_date" field.
func (u *ProjectUpsertBulk) ClearGitCommitDate() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearGitCommitDate()
	})
}

// SetNamespaceID sets the "namespace_id" field.
func (u *ProjectUpsertBulk) SetNamespaceID(v int) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetNamespaceID(v)
	})
}

// UpdateNamespaceID sets the "namespace_id" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateNamespaceID() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateNamespaceID()
	})
}

// ClearNamespaceID clears the value of the "namespace_id" field.
func (u *ProjectUpsertBulk) ClearNamespaceID() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearNamespaceID()
	})
}

// SetRepoID sets the "repo_id" field.
func (u *ProjectUpsertBulk) SetRepoID(v int) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetRepoID(v)
	})
}

// UpdateRepoID sets the "repo_id" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateRepoID() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateRepoID()
	})
}

// ClearRepoID clears the value of the "repo_id" field.
func (u *ProjectUpsertBulk) ClearRepoID() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearRepoID()
	})
}

// Exec executes the query.
func (u *ProjectUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProjectCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProjectCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProjectUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
