// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/settings/settings.proto

package settings

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_settings_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{0}
}

// ConfigItem 单条配置项。
type ConfigItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// 敏感配置脱敏展示（如密码/密钥）
	Masked        bool `protobuf:"varint,3,opt,name=masked,proto3" json:"masked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItem) Reset() {
	*x = ConfigItem{}
	mi := &file_proto_settings_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItem) ProtoMessage() {}

func (x *ConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItem.ProtoReflect.Descriptor instead.
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigItem) GetMasked() bool {
	if x != nil {
		return x.Masked
	}
	return false
}

// ConfigGroup 一组相关配置。
type ConfigGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Items         []*ConfigItem          `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigGroup) Reset() {
	*x = ConfigGroup{}
	mi := &file_proto_settings_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGroup) ProtoMessage() {}

func (x *ConfigGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGroup.ProtoReflect.Descriptor instead.
func (*ConfigGroup) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfigGroup) GetItems() []*ConfigItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*ConfigGroup         `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_settings_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetGroups() []*ConfigGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_proto_settings_settings_proto protoreflect.FileDescriptor

const file_proto_settings_settings_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/settings/settings.proto\x12\bsettings\x1a\x1cgoogle/api/annotations.proto\x1a\x1copenapi/v3/annotations.proto\"\f\n" +
	"\n" +
	"GetRequest\"L\n" +
	"\n" +
	"ConfigItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06masked\x18\x03 \x01(\bR\x06masked\"I\n" +
	"\vConfigGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x05items\x18\x02 \x03(\v2\x14.settings.ConfigItemR\x05items\"<\n" +
	"\vGetResponse\x12-\n" +
	"\x06groups\x18\x01 \x03(\v2\x15.settings.ConfigGroupR\x06groups2\x8a\x01\n" +
	"\bSettings\x12~\n" +
	"\x03Get\x12\x14.settings.GetRequest\x1a\x15.settings.GetResponse\"J\xbaG,\x12*平台配置聚合（管理员，只读）\x82\xd3\xe4\x93\x02\x15\x12\x13/api/admin/settingsB9Z7github.com/duc-cnzj/mars/api/v6/proto/settings;settingsb\x06proto3"

var (
	file_proto_settings_settings_proto_rawDescOnce sync.Once
	file_proto_settings_settings_proto_rawDescData []byte
)

func file_proto_settings_settings_proto_rawDescGZIP() []byte {
	file_proto_settings_settings_proto_rawDescOnce.Do(func() {
		file_proto_settings_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_settings_settings_proto_rawDesc), len(file_proto_settings_settings_proto_rawDesc)))
	})
	return file_proto_settings_settings_proto_rawDescData
}

var file_proto_settings_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_settings_settings_proto_goTypes = []any{
	(*GetRequest)(nil),  // 0: settings.GetRequest
	(*ConfigItem)(nil),  // 1: settings.ConfigItem
	(*ConfigGroup)(nil), // 2: settings.ConfigGroup
	(*GetResponse)(nil), // 3: settings.GetResponse
}
var file_proto_settings_settings_proto_depIdxs = []int32{
	1, // 0: settings.ConfigGroup.items:type_name -> settings.ConfigItem
	2, // 1: settings.GetResponse.groups:type_name -> settings.ConfigGroup
	0, // 2: settings.Settings.Get:input_type -> settings.GetRequest
	3, // 3: settings.Settings.Get:output_type -> settings.GetResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_settings_settings_proto_init() }
func file_proto_settings_settings_proto_init() {
	if File_proto_settings_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_settings_settings_proto_rawDesc), len(file_proto_settings_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_settings_settings_proto_goTypes,
		DependencyIndexes: file_proto_settings_settings_proto_depIdxs,
		MessageInfos:      file_proto_settings_settings_proto_msgTypes,
	}.Build()
	File_proto_settings_settings_proto = out.File
	file_proto_settings_settings_proto_goTypes = nil
	file_proto_settings_settings_proto_depIdxs = nil
}
