export const CREATE_PROJECT_LOADING = "CREATE_PROJECT_LOADING";
export const CREATE_PROJECT_LOADING_DONE = "CREATE_PROJECT_LOADING_DONE";
export const SET_CREATE_PROJECT_LOADING = "SET_CREATE_PROJECT_LOADING";
export const APPEND_CREATE_PROJECT_LOG = "APPEND_CREATE_PROJECT_LOG";
export const CLEAR_CREATE_PROJECT_LOG = "CLEAR_CREATE_PROJECT_LOG";
export const SET_DEPLOY_STATUS = "SET_DEPLOY_STATUS";
export const SET_PROCESS_PERCENT = "SET_PROCESS_PERCENT";

export const SET_NAMESPACE_RELOAD = "SET_NAMESPACE_RELOAD";

export const SET_CLUSTER_INFO = "SET_CLUSTER_INFO";
export const SET_SHELL_SESSION_ID = "SET_SHELL_SESSION_ID";
export const SET_SHELL_LOG = "SET_SHELL_LOG";
export const REMOVE_SHELL = "REMOVE_SHELL";

export const SET_TIMER_START = "SET_TIMER_START";
export const SET_TIMER_START_AT = "SET_TIMER_START_AT";

export const PROJECT_POD_EVENT = "PROJECT_POD_EVENT";
