export const CREATE_PROJECT_LOADING = "CREATE_PROJECT_LOADING";
export const CREATE_PROJECT_LOADING_DONE = "CREATE_PROJECT_LOADING_DONE";
export const SET_CREATE_PROJECT_LOADING = "SET_CREATE_PROJECT_LOADING";
export const APPEND_CREATE_PROJECT_LOG = "APPEND_CREATE_PROJECT_LOG";
export const CLEAR_CREATE_PROJECT_LOG = "CLEAR_CREATE_PROJECT_LOG";
export const SET_DEPLOY_STATUS = "SET_DEPLOY_STATUS";

export const SET_NAMESPACE_RELOAD = "SET_NAMESPACE_RELOAD";

