// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: cluster/cluster.proto

package cluster

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ClusterInfoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ClusterInfoResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClusterInfoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ClusterInfoResponseMultiError, or nil if none found.
func (m *ClusterInfoResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ClusterInfoResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	// no validation rules for FreeMemory

	// no validation rules for FreeCpu

	// no validation rules for FreeRequestMemory

	// no validation rules for FreeRequestCpu

	// no validation rules for TotalMemory

	// no validation rules for TotalCpu

	// no validation rules for UsageMemoryRate

	// no validation rules for UsageCpuRate

	// no validation rules for RequestMemoryRate

	// no validation rules for RequestCpuRate

	if len(errors) > 0 {
		return ClusterInfoResponseMultiError(errors)
	}
	return nil
}

// ClusterInfoResponseMultiError is an error wrapping multiple validation
// errors returned by ClusterInfoResponse.ValidateAll() if the designated
// constraints aren't met.
type ClusterInfoResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClusterInfoResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClusterInfoResponseMultiError) AllErrors() []error { return m }

// ClusterInfoResponseValidationError is the validation error returned by
// ClusterInfoResponse.Validate if the designated constraints aren't met.
type ClusterInfoResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClusterInfoResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClusterInfoResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClusterInfoResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClusterInfoResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClusterInfoResponseValidationError) ErrorName() string {
	return "ClusterInfoResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ClusterInfoResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClusterInfoResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClusterInfoResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClusterInfoResponseValidationError{}

// Validate checks the field values on ClusterInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ClusterInfoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClusterInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ClusterInfoRequestMultiError, or nil if none found.
func (m *ClusterInfoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ClusterInfoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ClusterInfoRequestMultiError(errors)
	}
	return nil
}

// ClusterInfoRequestMultiError is an error wrapping multiple validation errors
// returned by ClusterInfoRequest.ValidateAll() if the designated constraints
// aren't met.
type ClusterInfoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClusterInfoRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClusterInfoRequestMultiError) AllErrors() []error { return m }

// ClusterInfoRequestValidationError is the validation error returned by
// ClusterInfoRequest.Validate if the designated constraints aren't met.
type ClusterInfoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClusterInfoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClusterInfoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClusterInfoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClusterInfoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClusterInfoRequestValidationError) ErrorName() string {
	return "ClusterInfoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ClusterInfoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClusterInfoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClusterInfoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClusterInfoRequestValidationError{}
