name: CI
on: [push]
jobs:
  build-frontend:
    name: build-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          cache-dependency-path: frontend/yarn.lock
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd frontend install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd frontend build
      - name: upload build files
        uses: actions/upload-artifact@v2
        with:
          name: frontend_dist_files
          path: |
            frontend/build

  build-go:
    needs: [build-frontend]
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest, ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download frontend files
      uses: actions/download-artifact@v2
      with:
        name: frontend_dist_files
    - name: ls
      run: ls && ls frontend/build
    - name: Test
      run: go test ./...