name: CI
on: [push]
jobs:
  build-frontend:
    name: build-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd frontend install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd frontend build
      - name: upload build files
        uses: actions/upload-artifact@v2
        with:
          name: frontend_dist_files
          path: |
            frontend/build

  releases-matrix:
    needs: [build-frontend]
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - name: Download frontend files
        uses: actions/download-artifact@v2
        with:
          name: frontend_dist_files
          path: frontend/build
      - uses: wangyoucao577/go-release-action@v1.22
        with:
          goos: ${{ matrix.goos }}
          pre_command: export CGO_ENABLED=1
          goarch: ${{ matrix.goarch }}
          build_command: |
            make build