name: CI
on: [push]
jobs:
  build-frontend:
    name: build-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd frontend install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd frontend build
      - name: upload build files
        uses: actions/upload-artifact@v2
        with:
          name: frontend_dist_files
          path: |
            frontend/build

  releases-matrix:
    needs: [build-frontend]
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - name: Download frontend files
        uses: actions/download-artifact@v2
        with:
          name: frontend_dist_files
          path: frontend/build
      - uses: wangyoucao577/go-release-action@v1.22
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          build_command: |
            VERSION_PATH=$(go list -m -f "{{.Path}}")/version
            LDFLAGS = "-w -s  \
            -X ${VERSION_PATH}.gitRepo=$(go list -m -f "{{.Path}}") \
            -X ${VERSION_PATH}.gitBranch=$(git rev-parse --abbrev-ref HEAD) \
            -X ${VERSION_PATH}.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            -X ${VERSION_PATH}.gitCommit=$(git rev-parse --short HEAD) \
            -X ${VERSION_PATH}.gitTag=$(git describe --exact-match --tags HEAD 2> /dev/null || echo "") \
            -X ${VERSION_PATH}.kubectlVersion=$(go list -m -f "{{.Path}} {{.Version}}" all | grep k8s.io/client-go | cut -d " " -f2) \
            -X ${VERSION_PATH}.helmVersion=$(go list -m -f "{{.Path}} {{.Version}}" all | grep helm.sh/helm/v3 | cut -d " " -f2)"
            CGO_ENABLED=1 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags=${LDFLAGS} -o app-${{ matrix.goos }}-${{ matrix.goarch }} main.go
