name: release
on:
  push:
    tags-ignore:
      - 'api/*'

jobs:
  release-sdk:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: tag sdk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "1025434218@qq.com"
          git config --global user.name "duc"
          git config --global init.defaultBranch "master"

          git tag api/$GITHUB_ENV
          git push origin api/$GITHUB_ENV